trade_pipeline:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "US_SNOW_LLE_DEVELOPERS_RW_LG"
      database: "TRADE_PIPELINE_DB"
      warehouse: "DATA_TESTING_WH_XSMALL"
      schema: "STAGING"
      threads: 4
    ci:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "US_SNOW_LLE_DEVELOPERS_RW_LG"
      database: "TRADE_PIPELINE_DB"
      warehouse: "DATA_TESTING_WH_XSMALL"
      schema: "CI_STAGING"
      threads: 4
    prod:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "US_SNOW_LLE_DEVELOPERS_RW_LG"
      database: "TRADE_PIPELINE_DB"
      warehouse: "DATA_TESTING_WH_XSMALL"
      schema: "FINAL"
      threads: 4